# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: https://bn-bootnode-1.srv.focil-devnet-0.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-besu-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-besu-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-ethrex-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-ethrex-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-nethermind-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-nethermind-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-nethermind-2.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-nethermind-2
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-reth-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-reth-1
  authGroup: pandaops
  priority: -1
- url: https://bn-teku-besu-1.srv.focil-devnet-0.ethpandaops.io
  name: teku-besu-1
  authGroup: pandaops
  priority: -1
- url: https://bn-teku-ethrex-1.srv.focil-devnet-0.ethpandaops.io
  name: teku-ethrex-1
  authGroup: pandaops
  priority: -1
- url: https://bn-teku-ethrex-2.srv.focil-devnet-0.ethpandaops.io
  name: teku-ethrex-2
  authGroup: pandaops
  priority: -1
- url: https://bn-teku-ethrex-3.srv.focil-devnet-0.ethpandaops.io
  name: teku-ethrex-3
  authGroup: pandaops
  priority: -1
- url: https://bn-teku-reth-1.srv.focil-devnet-0.ethpandaops.io
  name: teku-reth-1
  authGroup: pandaops
  priority: -1

