# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: https://rpc-bootnode-1.srv.focil-devnet-0.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-bootnode-1.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-besu-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-besu-1.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-ethrex-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-ethrex-1.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-nethermind-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-nethermind-1.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-nethermind-2.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-nethermind-2.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-reth-1.srv.focil-devnet-0.ethpandaops.io
  name: lodestar-reth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-reth-1.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-besu-1.srv.focil-devnet-0.ethpandaops.io
  name: teku-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-besu-1.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-ethrex-1.srv.focil-devnet-0.ethpandaops.io
  name: teku-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-ethrex-1.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-ethrex-2.srv.focil-devnet-0.ethpandaops.io
  name: teku-ethrex-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-ethrex-2.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-ethrex-3.srv.focil-devnet-0.ethpandaops.io
  name: teku-ethrex-3
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-ethrex-3.srv.focil-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-reth-1.srv.focil-devnet-0.ethpandaops.io
  name: teku-reth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-reth-1.srv.focil-devnet-0.ethpandaops.io:8961
